name: myoro_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  # sdk: '>=3.5.0-254.0.dev <4.0.0'
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.9
  provider: ^6.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqlite3_flutter_libs: ^0.5.24
  path: ^1.9.0
  path_provider: ^2.1.3
  kiwi: ^5.0.0
  file_picker: ^8.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf