name: myoro_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-254.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.9
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf