name: "Frontend tests: Widget, unit, & line coverage tests"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get MyoroPlayer
        uses: actions/checkout@v3

      - name: Install Ubuntu dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 5
          max_attempts: 2
          command: sudo apt install -y lcov

      - name: Install Flutter using it's stable channel
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false

      - name: Disable Flutter animations to speed up the CI
        run: flutter config --no-cli-animations

      - name: Install Flutter dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 5
          max_attempts: 2
          retry_on: error
          command: cd frontend && flutter pub get

      - name: Run Dart fix (fails if any fixing or formatting occurs)
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 5
          max_attempts: 2
          command: cd frontend && dart fix --dry-run .

      - name: Run Dart format (fails if any fixing or formatting occurs)
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 5
          max_attempts: 2
          command: cd frontend && dart format --line-length 100 -o none --set-exit-if-changed .

      - name: Run widget, unit, & line coverage tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 5
          max_attempts: 2
          command: |
            cd frontend
            bash tools/test_and_generate_coverage_html.sh | grep "lines......: 100.0"